services:
  codementor:
    build:
      dockerfile: docker/codementor/Dockerfile
      context: .
    image: codementor
    container_name: codementor
    env_file:
      - docker/.env
    environment:
      - SHELLBOX_HOST=shellbox  # connect to the shellbox service
      - SHELLBOX_PORT=2222
    ports:
      - "5000:5000"
    entrypoint: ["python", "app/main.py", "--server"]
    restart: unless-stopped

  shellbox:
    build:
      dockerfile: docker/shellbox/Dockerfile
      context: .
    image: shellbox
    container_name: shellbox
    ports:
      - "2222:22"
    restart: unless-stopped

  shellbox-java:
    build:
      dockerfile: docker/shellbox-java/Dockerfile
      context: .
    image: shellbox-java
    container_name: shellbox-java
    ports:
      - "2223:22"
    restart: unless-stopped
