services:
  codementor:
    image: codepunx/codementor:latest
    container_name: codementor
    env_file:
      - docker/.env
    environment:
      - SHELLBOX_HOST=shellbox
      - SHELLBOX_PORT=22
    ports:
      - "5000:5000"
    entrypoint: ["python", "app/main.py", "--server"]
    restart: unless-stopped
    networks:
      - codementor-network

  shellbox:
    image: codepunx/shellbox-java:latest         # or shellbox
    container_name: shellbox
    ports:
      - "2222:22"
    restart: unless-stopped
    networks:
      - codementor-network

networks:
  codementor-network:
    driver: bridge