services:
  codementor:
    image: codepunx/codementor:latest
    container_name: codementor
    env_file:
      - docker/.env
    environment:
      - AI_MODEL_NAME=gpt-5-mini
      #- AI_MAX_OUTPUT_TOKENS=2000
      #- AI_MAX_PROMPT_LENGTH=2000    
      - SHELLBOX_HOST=shellbox
      - SHELLBOX_PORT=22
      - SHELLBOX_USER=mentor
      - COMMAND_TIMEOUT=120
      - COMMAND_INACTIVITY_TIMEOUT=60
      #- LOGLEVEL=INFO
      - LOGFORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    ports:
      - "5000:5000"
    entrypoint: ["python", "app/main.py", "--server"]
    restart: always
    networks:
      - codementor-network
    volumes:
      - codementor-data:/home/mentor/workflows
      - codementor-log:/var/log/mentor


  shellbox:
    image: codepunx/shellbox-java:latest         # or shellbox
    container_name: shellbox
    ports:
      - "2222:22"
    restart: always
    networks:
      - codementor-network



networks:
  codementor-network:
    driver: bridge

volumes:
  codementor-data:
    driver: local
  codementor-log:
    driver: local

